name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # roda todo dia
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        with:
          github_user_name: LaizVerlane
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
      - name: Commit snake
        uses: EndBug/add-and-commit@v9
        with:
          message: "Atualiza cobrinha 🐍"
          add: "dist/*.svg"
