name: Metrics

on:
  schedule: [{cron: "0 0 * * 0"}]  # roda todo domingo
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_repositories: yes
          plugin_repositories_featured: LaizVerlane/ml-projeto, LaizVerlane/bling-powerbi
